#!/usr/bin/env python3
import argparse
import json

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('json')

    args = parser.parse_args()
    print(json.loads(args.json))
