#!/usr/bin/env python3
import argparse
from zoneinfo import ZoneInfo
from datetime import datetime, timezone


def main(tz):
    tzinfo = None
    if tz != 'local':
        tzinfo = ZoneInfo(tz) if tz else timezone.utc
    print(datetime.now(tz=tzinfo))
    
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--tz', nargs='?', type=str, default=None)

    args = parser.parse_args()
    main(args.tz)
