#!/usr/bin/env python3
import argparse

import arrow


def main(utc_time):
    if utc_time:
        print(arrow.get(utc_time).to('US/Central'))
    else:
        print(arrow.utcnow())

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('utc_time', nargs='?', type=str, default=None)

    args = parser.parse_args()
    main(args.utc_time)
