on: ['pull_request']

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Run shellcheck on my scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          path: '.'
          pattern: '*.sh'
          exclude: './.git/*'
